---
# Install
- name: Add Elasticsearch repository.
  copy:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo
    mode: 0644


# Configure
- name: Install Elasticsearch.
  yum: pkg=elasticsearch state=installed

- name: Configure Elasticsearch.
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0750
  notify: restart elasticsearch


# Run
- name: Start Elasticsearch.
  service: name=elasticsearch state=started enabled=yes

    #- name: Make sure Elasticsearch is running before proceeding.
    #  wait_for: host={{ elasticsearch_network_host }} port={{ elasticsearch_http_port }} delay=3 timeout=300
