# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.ssh.insert_key = false
    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
    end

    # bastion
    config.vm.define "bastion" do |bastion|
        bastion.vm.hostname = "bastion"
        bastion.vm.box = "fedora/24-cloud-base"
        bastion.vm.network :private_network, ip: "192.168.70.10"
    end
end

