---

# Add GPG key
- hosts: all
  roles:
    - GPG_repo_key


# Install java
- hosts: elastic,logstash
  roles:
    - java


# Install, config and run elastic
- hosts: elastic
  roles:
    - elasticsearch


# Install logstash
- hosts: logstash
  roles:
    - logstash


# Install kibana 
- hosts: kibana
  roles:
      #- nginx
      #- kibana
