---
# Install java to all hosts
- hosts: all
  roles:
    - install_java

# Install, config and run elastic
- hosts: elastic
  vars_files:
    - vars/elasticsearch_vars.yml
  roles:
    - elasticsearch

# Install logstash
- hosts: logstash
  roles:
    - logstash

# Install kibana 
