---
 # SSH

 - name: Setting ssh MaxSessions and Permit root access
   become: yes
   lineinfile:
     dest: "/etc/ssh/sshd_config"
     regexp: "MaxSessions"
     line: "MaxSessions {{ MaxSessions }}"
     state: present
   lineinfile:
     dest: "/etc/ssh/sshd_config"
     regexp: "PermitRootLogin yes$"
     line: "PermitRootLogin {{ PermitRootLogin }}"
     state: present
   notify: restart sshd