---
 # SSH
 - name: Permit root access
   become: yes
   lineinfile:
     dest: "/etc/ssh/sshd_config"
     regexp: "PermitRootLogin yes$"
     line: "PermitRootLogin no"
     state: present

 - name: Setting ssh MaxSessions
   become: yes
   lineinfile:
     dest: "/etc/ssh/sshd_config"
     regexp: "MaxSessions"
     line: "MaxSessions {{ MaxSessions }}"
     state: present
   notify: restart sshd


